### ISSUE TITLE
Rotation currently throws an exception

### ISSUE THREAD

**Issue by sjdodge123** [rtoole13/Wayfarer#8]
Exception: Inappropriately formated direction vector. x and y coordinates must be -1, 0, or 1.
UnitController.RotationFromDirection (Int32 dirX, Int32 dirY) (at Assets/Scripts/UnitController.cs:112)
UnitController+<FollowPath>c__Iterator0.MoveNext () (at Assets/Scripts/UnitController.cs:67)
UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress) (at C:/buildslave/unity/build/Runtime/Export/Coroutines.cs:17)

is thrown when player clicks while the ship is in motion

**Comment by rtoole13** [comment]
This might be because as the ship moves through hexes on its path, the ship updates its 'nodeLocation' reference. If the ship's in transit between nodes and a new path is selected, the direction vector could be getting a difference between a target node and a non-immediately-adjacent node, causing an incorrect direction vector  outside the 6 possibilities.

We should probably just consider a 'moving' bool that doesn't let you request a new  path while you are moving. At least, that'd be the easiest solution.

**Comment by rtoole13** [comment]
Can no longer request a path while currently on a path. Bypasses this issue.
